import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto, Road_Rage, Alatsi } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const jejuMyeongjoFont = localFont({
	src: "../../public/fonts/JejuMyeongjo.woff",
	display: "swap",
	variable: "--font-jejumyeongjo",
});

const roboto = Roboto({
	weight: ["400", "500", "700", "900"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto",
});
const alatsi = Alatsi({
	weight: ["400"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-alatsi",
});
const roadrage = Road_Rage({ weight: ["400"], subsets: ["latin"], display: "swap", variable: "--font-road-rage" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${jejuMyeongjoFont.variable} ${roboto.variable} ${roadrage.variable} ${alatsi.variable} w-screen min-h-screen font-jejumyeongjo antialiased text-white !px-5 lg:!px-[7.5rem] !py-2.5 md:!py-6  bg-custom-gradient flex flex-col gap-[18px] md:gap-[2.875rem] items-center !pb-[42px] md:!pb-[88px]`}>
				<div className="!px-5 lg:!px-[7.5rem] !pt-5 md:!pt-8 w-full flex justify-center z-50 fixed">
					<NavBar />
				</div>
				<main className="w-screen h-full lg:!flex !flex-col !items-center  pt-[88px] md:!pt-32  !px-5">{children}</main>
			</body>
		</html>
	);
}
